name: Build firmware
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:


jobs:
  build-firmware:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keyboard:
          # - ergodox_ez
          # - ergodox_ez/shine
          # - ergodox_ez/glow
          # - moonlander
          # - planck/ez
          # - planck/ez/glow
          - voyager
          # - voyager/gd32
        keymap:
          - default
          - oryx
          - fc

    steps:
    - name: Checkout QMK Firmware
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        persist-credentials: false
        submodules: true

    - name: Build
      id: build
      run: |
        qmk compile -kb ${{ matrix.keyboard}} -km ${{ matrix.keymap }}


  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: zsa/qmk_firmware
      qmk_ref: main

  publish:
    name: 'QMK Userspace Publish'
    uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@main
    if: always() && !cancelled()
    needs: build
